<a href="https://colab.research.google.com/github/bhushanmandava/PyTorch_fundamentals/blob/main/Funda_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd


In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
!nvidia-smi


Fri Jun 20 17:24:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
scalr = torch.tensor(7)
#torch. tensor is the most basic class in the PyTorch tensors to make our data ready to turn into to tensor

In [5]:
scalr

tensor(7)

In [6]:
scalr.ndim #ndim is way to reffer to the dimension or get the dimensions of the tensors in the pytorch

0

In [7]:
scalr.item()

7

In [8]:
#creating the vector
vector = torch.tensor([7,7])

In [9]:
vector. ndim# so it is only one-dimensional

1

In [10]:
vector.shape# the shape is 2X1 elemenrts

torch.Size([2])

In [11]:
matrix = torch.tensor([[7,8,10],[8,9,10]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 3])

In [14]:
tensor = torch.tensor([[[1,2],[2,3],[3,4]],
                      [[1,2],[2,3],[3,5]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([2, 3, 2])

In [17]:
tensor[1][2][1]#this is the representation, it is always the outer layer(rows x columns) _> each outer layer or dim has its own rows and columns

tensor(5)

In [18]:
#playing with the random tensors
random_tensor = torch.rand(10,3,4)

In [19]:
random_tensor

tensor([[[0.3446, 0.0151, 0.5965, 0.0920],
         [0.8483, 0.4582, 0.1917, 0.2019],
         [0.8112, 0.6294, 0.1877, 0.5403]],

        [[0.6441, 0.0413, 0.4721, 0.5078],
         [0.8409, 0.1954, 0.4100, 0.6847],
         [0.3000, 0.0521, 0.4259, 0.3273]],

        [[0.4584, 0.3203, 0.3919, 0.9405],
         [0.0905, 0.0409, 0.1693, 0.8961],
         [0.3646, 0.3713, 0.2824, 0.9725]],

        [[0.7985, 0.8093, 0.8912, 0.3170],
         [0.7587, 0.2426, 0.8521, 0.5835],
         [0.1343, 0.3051, 0.3018, 0.2581]],

        [[0.4548, 0.6947, 0.6144, 0.8079],
         [0.6431, 0.5973, 0.5773, 0.5206],
         [0.3730, 0.3415, 0.6586, 0.9831]],

        [[0.4756, 0.7437, 0.8920, 0.5387],
         [0.9891, 0.3222, 0.9320, 0.3545],
         [0.8560, 0.2480, 0.0294, 0.4630]],

        [[0.7282, 0.1417, 0.0082, 0.8970],
         [0.8580, 0.0123, 0.7786, 0.3334],
         [0.7550, 0.6893, 0.6181, 0.4466]],

        [[0.9991, 0.9392, 0.6075, 0.9495],
         [0.8576, 0.5492, 0.6513, 0.8446

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([10, 3, 4])

In [22]:
#creating the image tesnor
random_image_size_tensor = torch.rand(size=(224,224,3))#row coloums 3 reffers to RGB

In [23]:
random_image_size_tensor

tensor([[[0.8735, 0.0095, 0.7026],
         [0.6434, 0.5330, 0.5725],
         [0.8202, 0.1757, 0.2053],
         ...,
         [0.0978, 0.0298, 0.5513],
         [0.5049, 0.3484, 0.2418],
         [0.8330, 0.2707, 0.4313]],

        [[0.3926, 0.2366, 0.4174],
         [0.7446, 0.3843, 0.3766],
         [0.3795, 0.3140, 0.7221],
         ...,
         [0.0682, 0.2992, 0.6044],
         [0.2847, 0.6900, 0.6396],
         [0.7606, 0.4859, 0.3224]],

        [[0.5116, 0.3860, 0.9638],
         [0.9601, 0.7540, 0.6365],
         [0.3663, 0.0957, 0.0218],
         ...,
         [0.8400, 0.2085, 0.6689],
         [0.4564, 0.2297, 0.6192],
         [0.1221, 0.6660, 0.3692]],

        ...,

        [[0.8000, 0.1211, 0.6807],
         [0.8455, 0.6780, 0.2107],
         [0.0923, 0.3944, 0.4616],
         ...,
         [0.5140, 0.5075, 0.0761],
         [0.6821, 0.1139, 0.3670],
         [0.0610, 0.3472, 0.4536]],

        [[0.3348, 0.3075, 0.1160],
         [0.5826, 0.6146, 0.4112],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [26]:
# creatin the mask ie(creating the tensors with the zeros)
zero = torch.zeros(3,4)
ones = torch.ones(3,4)# you can also create the tensor with ones

In [27]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
# creating the torch with a certain range in the maind
one_to_ten=torch.arange(0,10,2)#here the the 3rd attribute is the steps

In [30]:
one_to_ten

tensor([0, 2, 4, 6, 8])

In [31]:
# datas types on the tensors
tensor = torch.tensor([1.,2.,3.])#the basic data type is float 32. You can also create the integer data type. You have to use float 16 if you want to use MPS 32-bit single precision, 16 half precision, and 64-bit double precision

### usual error
not on the right data type or device or the right shape

In [32]:
tensor.dtype

torch.float32

## playing with tensor ops
-> addition
-> sub
-> divison
-> mat multiplication

In [33]:
tensor = torch.ones(3,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
tensor+20

tensor([[21., 21., 21., 21.],
        [21., 21., 21., 21.],
        [21., 21., 21., 21.]])

In [35]:
tensor# oops we forgot to reassign the code

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
tensor/1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
tensor2= torch.ones(3,4) *10

In [38]:
torch.mul(tensor,tensor2)# problem is 3*4  #note remeber this is element wise multiplicatiom wich is not matric multiplicatioj

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [39]:
torch.matmul(tensor,tensor2) # rember this mul is  not same as matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [40]:
tensor2 = tensor2.reshape(4,3)

In [41]:
torch.matmul(tensor,tensor2)

tensor([[40., 40., 40.],
        [40., 40., 40.],
        [40., 40., 40.]])

In [58]:
#reshaping, viewing, and stacking squeezing and unsqueezeing
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Reshaping
* reshaping is changing the shape of input tensor
* View - share same memory and every thing similar to reshaping
* stacking - combine the multile tensor on top of each other
* squeeze - removes all '1' dimensions from tensor

In [59]:
tensor , tensor.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [60]:
tensor.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
z=tensor.view(1,9)# similar to the reshape but here we utilize the same memory

In [62]:
tensor.shape

torch.Size([3, 3])

In [63]:
z[:,0]=2

In [64]:
z

tensor([[2, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
tensor

tensor([[2, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [83]:
### lets do stacking
x = torch.arange(1.,20.,2)
y = torch.arange(1.,20.,2)
x.shape,y.shape
x=x.reshape(5,2)
y=y.reshape(5,2)

In [99]:
x_stacked_y = torch.stack([x,y],dim=2)

In [100]:
x_stacked_y.shape

torch.Size([5, 2, 2])

In [101]:
x_stacked_y

tensor([[[ 1.,  1.],
         [ 3.,  3.]],

        [[ 5.,  5.],
         [ 7.,  7.]],

        [[ 9.,  9.],
         [11., 11.]],

        [[13., 13.],
         [15., 15.]],

        [[17., 17.],
         [19., 19.]]])

In [103]:
#squeeeze
x_stacked_y.shape

torch.Size([5, 2, 2])

In [105]:
temp=x_stacked_y.squeeze()

In [108]:
temp= temp.reshape(1,20)

In [109]:
temp.shape

torch.Size([1, 20])

In [111]:
temp.squeeze().shape # we removeed our 1 dimensions

torch.Size([20])

In [112]:
temp

tensor([[ 1.,  1.,  3.,  3.,  5.,  5.,  7.,  7.,  9.,  9., 11., 11., 13., 13.,
         15., 15., 17., 17., 19., 19.]])

In [117]:
temp.unsqueeze(dim=0)

tensor([[[ 1.,  1.,  3.,  3.,  5.,  5.,  7.,  7.,  9.,  9., 11., 11., 13., 13.,
          15., 15., 17., 17., 19., 19.]]])

In [118]:
temp.shape

torch.Size([1, 20])

In [121]:
temp.unsqueeze(dim=1)

tensor([[[ 1.,  1.,  3.,  3.,  5.,  5.,  7.,  7.,  9.,  9., 11., 11., 13., 13.,
          15., 15., 17., 17., 19., 19.]]])

In [122]:
temp.shape

torch.Size([1, 20])

In [125]:
# permuting
n= torch.rand(size=(224,224,3))

In [126]:
n.permute(2,1,0)

tensor([[[0.3984, 0.4078, 0.9199,  ..., 0.0756, 0.9243, 0.7907],
         [0.0968, 0.7973, 0.9332,  ..., 0.3610, 0.6224, 0.2795],
         [0.6708, 0.2201, 0.7539,  ..., 0.6928, 0.9098, 0.1524],
         ...,
         [0.4043, 0.5242, 0.8238,  ..., 0.6907, 0.4499, 0.9005],
         [0.1655, 0.1962, 0.3250,  ..., 0.5593, 0.9728, 0.9284],
         [0.8484, 0.7810, 0.1747,  ..., 0.6918, 0.6568, 0.7100]],

        [[0.2946, 0.7359, 0.1500,  ..., 0.9206, 0.4168, 0.2710],
         [0.1238, 0.7300, 0.0126,  ..., 0.3545, 0.0625, 0.0107],
         [0.3751, 0.5116, 0.4362,  ..., 0.6879, 0.5676, 0.1602],
         ...,
         [0.5925, 0.7683, 0.2634,  ..., 0.9204, 0.0631, 0.1732],
         [0.9540, 0.5361, 0.4587,  ..., 0.2501, 0.5477, 0.5534],
         [0.3441, 0.2263, 0.3522,  ..., 0.0920, 0.6120, 0.2356]],

        [[0.2224, 0.1127, 0.4190,  ..., 0.5980, 0.2084, 0.8722],
         [0.2169, 0.4683, 0.9507,  ..., 0.1329, 0.3451, 0.5510],
         [0.1488, 0.3320, 0.3788,  ..., 0.1385, 0.2590, 0.

In [127]:
n[0][0][1]=2

In [128]:
n

tensor([[[0.3984, 2.0000, 0.2224],
         [0.0968, 0.1238, 0.2169],
         [0.6708, 0.3751, 0.1488],
         ...,
         [0.4043, 0.5925, 0.9171],
         [0.1655, 0.9540, 0.0470],
         [0.8484, 0.3441, 0.5356]],

        [[0.4078, 0.7359, 0.1127],
         [0.7973, 0.7300, 0.4683],
         [0.2201, 0.5116, 0.3320],
         ...,
         [0.5242, 0.7683, 0.8275],
         [0.1962, 0.5361, 0.9940],
         [0.7810, 0.2263, 0.1053]],

        [[0.9199, 0.1500, 0.4190],
         [0.9332, 0.0126, 0.9507],
         [0.7539, 0.4362, 0.3788],
         ...,
         [0.8238, 0.2634, 0.3749],
         [0.3250, 0.4587, 0.6028],
         [0.1747, 0.3522, 0.4255]],

        ...,

        [[0.0756, 0.9206, 0.5980],
         [0.3610, 0.3545, 0.1329],
         [0.6928, 0.6879, 0.1385],
         ...,
         [0.6907, 0.9204, 0.3936],
         [0.5593, 0.2501, 0.5408],
         [0.6918, 0.0920, 0.2462]],

        [[0.9243, 0.4168, 0.2084],
         [0.6224, 0.0625, 0.3451],
         [0.

In [130]:
#working on the indexing
x = torch.arange(1,10).reshape(1,3,3)

In [131]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [132]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [134]:
x[0][0][0]

tensor(1)

In [135]:
x[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [136]:
x[0][2][3]

IndexError: index 3 is out of bounds for dimension 0 with size 3

In [137]:
x[0][2][2]

tensor(9)

In [138]:
x[0,2,2]

tensor(9)

In [142]:
x[:,:,2].reshape(3,1)

tensor([[3],
        [6],
        [9]])

In [143]:
x[0,0,: ]

tensor([1, 2, 3])